# Generated by Django 5.2.8 on 2025-11-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Dernière Modification')),
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('theme', models.CharField(blank=True, choices=[('CS_AI', 'Computer Science & Artificial Intelligence'), ('SE', 'Science & Engineering'), ('SS_EDU', 'Social Sciences & Education'), ('INTER', 'Interdisciplinary Themes')], max_length=50, null=True)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Dernière Modification')),
                ('committee_role', models.CharField(choices=[('chair', 'Chair'), ('co_chair', 'Co-Chair'), ('member', 'Member'), ('review_coord', 'Review Coordinator')], max_length=50)),
                ('date_joined', models.DateField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConferenceApp.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
            options={
                'unique_together': {('user', 'conference')},
            },
        ),
        migrations.AddField(
            model_name='conference',
            name='organizers',
            field=models.ManyToManyField(related_name='conferences_organized', through='ConferenceApp.OrganizingCommittee', to='UserApp.user'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Dernière Modification')),
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('topic', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=500)),
                ('paper_file', models.FileField(blank=True, null=True, upload_to='papers/', verbose_name='Article Soumis')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('payed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_authored', to='UserApp.user')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ConferenceApp.conference')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
