# Generated by Django 5.2.8 on 2025-11-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Dernière Modification')),
                ('user_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('organisateur', 'Organisateur'), ('comite_scientifique', 'Membre du Comité Scientifique')], default='participant', max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
